class CodeGenerator:



    def generate(

        self,

        objects

    ):


        code = []


        code.append(

            "// ESPHome E-Ink Screen"

        )


        code.append(

            "// Generated by ESPHome E-Ink Designer"

        )


        code.append(

            ""

        )



        for obj in objects:



            # ---------------------
            # TEXTE
            # ---------------------

            if obj.type == "text":



                line = (

                    f'it.print('

                    f'{obj.x}, '

                    f'{obj.y}, '

                    f'id({obj.font}), '

                    f'{obj.align}, '

                    f'{obj.value});'

                )



                code.append(line)




            # ---------------------
            # IMAGE
            # ---------------------

            elif obj.type == "image":



                line = (

                    f'it.image('

                    f'{obj.x}, '

                    f'{obj.y}, '

                    f'id({obj.image}));'

                )


                code.append(line)




            # ---------------------
            # RECTANGLE
            # ---------------------

            elif obj.type == "rectangle":



                line = (

                    f'it.rectangle('

                    f'{obj.x}, '

                    f'{obj.y}, '

                    f'{obj.width}, '

                    f'{obj.height}, '

                    'COLOR_ON);'

                )


                code.append(line)



        return "\n".join(code)
